apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - deployment-analytics-writer.yaml

namespace: trading-bot

commonLabels:
  app: trading-bot
  component: analytics-writer
  tier: analytics

commonAnnotations:
  node-affinity: master-only