import pandas as pd
import numpy as np
import torch
from sklearn.preprocessing import MinMaxScaler
from datasets import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    BitsAndBytesConfig,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer
import warnings
warnings.filterwarnings("ignore")

# --- 1. LOAD & PREPARE DATA ---
def load_and_preprocess_data(filepath="crypto_data.csv"):
    """Loads the data generated by get_data.py and prepares it for training."""
    df = pd.read_csv(filepath)

    # Filter for BTC/EUR data only (or adjust for multiple coins)
    df = df[df['coin'] == 'BTC/EUR'].copy()

    # Normalisation (0-1 for technical indicators)
    scaler = MinMaxScaler()
    df[["rsi", "macd", "volume"]] = scaler.fit_transform(df[["rsi", "macd", "volume"]])

    # Create labels based on future price movement
    df["future_return"] = df["close"].pct_change(3).shift(-3)  # 3-day return
    df["label"] = np.where(df["future_return"] > 0.02, "kaufen",
                          np.where(df["future_return"] < -0.02, "verkaufen", "halten"))
    df = df.dropna()

    # Convert timestamp back to milliseconds (for consistency)
    df['timestamp'] = (pd.to_datetime(df['timestamp']).astype(np.int64) // 10**6)

    return df

# --- 2. PROMPT CREATION (ADAPTED FOR MULTI-COIN) ---
def create_prompt(row):
    """Creates a natural text prompt from the data."""
    return f"""
    Current market data for {row['coin']}:
    - Date: {pd.to_datetime(row['timestamp'], unit='ms').strftime('%Y-%m-%d')}
    - Price: Open={row['open']:.2f}, High={row['high']:.2f}, Low={row['low']:.2f}, Close={row['close']:.2f}
    - Volume: {row['volume']:.2f} (normalised)
    - Indicators:
      - RSI: {row['rsi']:.2f} (0=oversold, 1=overbought)
      - MACD: {row['macd']:.2f} (negative=downtrend, positive=uptrend)

    Question: Should I buy, sell, or hold? Answer with one word only: kaufen/verkaufen/halten.
    Answer: {row['label']}
    """

# --- 3. CREATE FINE-TUNING DATASET ---
def prepare_dataset(df):
    """Converts the DataFrame into a Hugging Face Dataset."""
    prompts = [create_prompt(row) for _, row in df.iterrows()]
    return Dataset.from_dict({"text": prompts})

# --- 4. LOAD & CONFIGURE MODEL ---
def load_model():
    """Loads Mistral-7B with 4-bit quantisation for the RTX 3090."""
    model_name = "mistralai/Mistral-7B-v0.1"

    # 4-bit quantisation
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
    )

    # Load model & tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=bnb_config,
        device_map="auto",
    )

    model = prepare_model_for_kbit_training(model)
    return model, tokenizer

# --- 5. LoRA CONFIGURATION ---
def get_lora_config():
    """Configures Low-Rank Adaptation (LoRA)."""
    return LoraConfig(
        r=8,
        lora_alpha=16,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
    )

# --- 6. TRAINING (ADJUSTED PARAMETERS) ---
def train(model, tokenizer, dataset):
    """Fine-tunes the model with the prepared data."""
    training_args = TrainingArguments(
        output_dir="./results",
        per_device_train_batch_size=2,  # Reduced for better compatibility
        gradient_accumulation_steps=4,
        learning_rate=2e-5,
        num_train_epochs=3,
        fp16=True,
        save_steps=100,
        logging_steps=10,
        optim="paged_adamw_8bit",
        warmup_ratio=0.1,  # Added for more stable training
        max_grad_norm=0.3,  # Gradient Clipping
    )

    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=dataset,
        dataset_text_field="text",
        tokenizer=tokenizer,
        max_seq_length=512,
    )

    print("🚀 Training starting...")
    trainer.train()
    print("✅ Training complete!")

    # Save the model
    model.save_pretrained("./fine_tuned_trading_model")
    tokenizer.save_pretrained("./fine_tuned_trading_model")

# --- 7. MAIN PROGRAM (WITH DATA VALIDATION) ---
if __name__ == "__main__":
    print("📊 Loading data...")
    try:
        df = load_and_preprocess_data()
        print(f"📈 Found records: {len(df)}")

        if len(df) < 100:
            raise ValueError("Too few records - please collect more historical data")

        print("💾 Creating dataset...")
        dataset = prepare_dataset(df)

        print("🤖 Loading model...")
        model, tokenizer = load_model()
        model = get_peft_model(model, get_lora_config())

        print("🎓 Training...")
        train(model, tokenizer, dataset)

        print("🎉 Model saved to './fine_tuned_trading_model'!")
    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
        print("\n🔍 Tips:")
        print("1. Check whether 'crypto_data.csv' exists")
        print("2. Make sure enough VRAM is available")
        print("3. Try: python3 train_trading_model.py")
